name: Replicate Huggingface

on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "Model ID"
        required: true

jobs:
  replicate_huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "replicate-huggingface/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r replicate-huggingface/requirements.txt
