name: Replicate Civitai Model

on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "Model ID"
        required: true

jobs:
  replicate_huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup jq
        uses: dcarbone/install-jq-action@v3

      - name: Setup coscli
        env:
          COSCLI_CONFIG_BASE64: ${{ secrets.COS_CLI_CONFIG_BASE64_ASSETS }}
        run: |
          curl -sSLo coscli 'https://github.com/tencentyun/coscli/releases/download/v1.0.3/coscli-v1.0.3-linux-amd64'
          chmod +x coscli
          echo $COSCLI_CONFIG_BASE64 | base64 -d > ~/.cos.yaml
          ./coscli ls cos://assets

      - name: Download and Replicate Model
        run: |
          curl -sSL -H 'Authorization: Bearer ${{ secrets.CIVITAI_API_KEY }}' -o model.json "https://api.civitai.com/models/${{ github.event.inputs.model_id }}"
          mkdir -p dl
          jq -c '.modelVersions[0].files[]' | while read -r item; do
            filename="dl/$(echo "$item" | jq -r '.name')"
            file_url="$(echo "$item" | jq -r '.downloadUrl')"
            echo curl -sSL -H 'Authorization: Bearer ${{ secrets.CIVITAI_API_KEY }}' -o "$filename" "$file_url"
          done
          echo ./coscli cp -r --part-size 128 "dl/" "cos://assets/civitai.com/models/${{ github.event.inputs.model_id }}/"
