name: Replicate Civitai Model

on:
  workflow_dispatch:
    inputs:
      model_id:
        description: "Model ID"
        required: true

jobs:
  replicate_civitai_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup jq
        uses: dcarbone/install-jq-action@v3

      - name: Setup coscli
        env:
          COSCLI_CONFIG_BASE64: ${{ secrets.COS_CLI_CONFIG_BASE64_ASSETS }}
        run: |
          curl -sSLo coscli 'https://github.com/tencentyun/coscli/releases/download/v1.0.3/coscli-v1.0.3-linux-amd64'
          chmod +x coscli
          echo $COSCLI_CONFIG_BASE64 | base64 -d > ~/.cos.yaml
          ./coscli ls cos://assets

      - name: Download and Replicate Model
        env:
          CIVITAI_API_KEY: ${{ secrets.CIVITAI_API_KEY }}
        run: |
          curl -sSL -H "Authorization: Bearer $CIVITAI_API_KEY" -o model.json "https://civitai.com/api/v1/models/${{ github.event.inputs.model_id }}"
          mkdir -p dl
          jq -c '.modelVersions[0].files[]' model.json | while read -r item; do
            FILENAME="dl/$(echo "$item" | jq -r '.name')"
            FILE_URL="$(echo "$item" | jq -r '.downloadUrl')"
            curl -sSL -H "Authorization: Bearer $CIVITAI_API_KEY" -o "$FILENAME" "$FILE_URL"
          done
          ./coscli cp -r --part-size 128 "dl/" "cos://assets/civitai.com/models/${{ github.event.inputs.model_id }}/"
